// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tBXAJDTtMz8jWSodQndvpQHGW5VY_D0',
    appId: '1:500611087806:web:f7a9e6aa8773cc1b170def',
    messagingSenderId: '500611087806',
    projectId: 'hostelmanagement-59abd',
    authDomain: 'hostelmanagement-59abd.firebaseapp.com',
    storageBucket: 'hostelmanagement-59abd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5u5Z5tPM63fj3Vx2Oowx65yZiGcE2Jg4',
    appId: '1:500611087806:android:23d6cd317ff180a2170def',
    messagingSenderId: '500611087806',
    projectId: 'hostelmanagement-59abd',
    storageBucket: 'hostelmanagement-59abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1mQO8Cl-kpvtp2-VWYVbfBLMUJnzmEYI',
    appId: '1:500611087806:ios:1ccdf79bcbec7f64170def',
    messagingSenderId: '500611087806',
    projectId: 'hostelmanagement-59abd',
    storageBucket: 'hostelmanagement-59abd.firebasestorage.app',
    iosBundleId: 'com.example.hostelmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1mQO8Cl-kpvtp2-VWYVbfBLMUJnzmEYI',
    appId: '1:500611087806:ios:1ccdf79bcbec7f64170def',
    messagingSenderId: '500611087806',
    projectId: 'hostelmanagement-59abd',
    storageBucket: 'hostelmanagement-59abd.firebasestorage.app',
    iosBundleId: 'com.example.hostelmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_tBXAJDTtMz8jWSodQndvpQHGW5VY_D0',
    appId: '1:500611087806:web:db8f5a60ffc77c53170def',
    messagingSenderId: '500611087806',
    projectId: 'hostelmanagement-59abd',
    authDomain: 'hostelmanagement-59abd.firebaseapp.com',
    storageBucket: 'hostelmanagement-59abd.firebasestorage.app',
  );

}